using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Tam.Compiler;

/// <summary>
/// Compile-time discovery (docs/12): emits an <c>AddDiscovered()</c> extension registering every
/// [Operation], [View], and [ServerDerivation] host in the compilation — the model is explicit,
/// generated, and inspectable on disk instead of found by runtime assembly scanning (docs/01).
/// </summary>
[Generator]
public sealed class TamSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var operations = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.OperationAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        var views = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.ViewAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        var derivationHosts = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.ServerDerivationAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol.ContainingSymbol))
            .Collect();

        var all = operations.Combine(views).Combine(derivationHosts);

        context.RegisterSourceOutput(all, static (spc, source) =>
        {
            var ((ops, viewTypes), hosts) = source;
            if (ops.IsEmpty && viewTypes.IsEmpty && hosts.IsEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> Tam.Compiler compile-time discovery.");
            sb.AppendLine("namespace Tam.Generated;");
            sb.AppendLine();
            // Internal: every assembly (host and each plugin) gets its own discovery class, and
            // referencing a plugin assembly must not make the host's AddDiscovered() ambiguous.
            sb.AppendLine("internal static class TamDiscovered");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Registers everything the compiler found — no runtime assembly scan.</summary>");
            sb.AppendLine("    public static global::Tam.TamModelBuilder AddDiscovered(this global::Tam.TamModelBuilder builder)");
            sb.AppendLine("    {");
            foreach (var op in ops.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddOperationType(typeof({op}));");
            foreach (var view in viewTypes.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddViewType(typeof({view}));");
            foreach (var host in hosts.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddDerivationHost(typeof({host}));");
            sb.AppendLine("        return builder;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("TamDiscovered.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static string Qualified(ISymbol symbol) =>
        symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
}
