using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Tam.Compiler;

/// <summary>
/// Compile-time discovery (docs/12): emits an <c>AddDiscovered()</c> extension registering every
/// [Operation], [View], and [ServerDerivation] host in the compilation — the model is explicit,
/// generated, and inspectable on disk instead of found by runtime assembly scanning (docs/01).
/// </summary>
[Generator]
public sealed class TamSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Slice 3 (docs/31): a referenced host-contract.json (AdditionalFile) is the host's
        // exported extension surface — the plugin author's "what can I extend?" answer made
        // IntelliSense. docs/37 D-V4 adds a SECOND provider: a dependent plugin also references
        // its parent's `<parent>.contract.json` slice, and the facades union across every
        // referenced artifact (ids are globally namespaced, PLG001, so a merged index cannot
        // collide). With any artifact present it is the facade source of truth; the
        // declaration-derived facades below stay as the artifact-less fallback.
        var contractArtifacts = context.AdditionalTextsProvider
            .Where(static t =>
            {
                var name = System.IO.Path.GetFileName(t.Path);
                return name.Equals("host-contract.json", System.StringComparison.OrdinalIgnoreCase)
                    || name.EndsWith(".contract.json", System.StringComparison.OrdinalIgnoreCase);
            })
            .Select(static (t, ct) => t.GetText(ct)?.ToString() ?? "")
            .Collect();

        AddContractFacades(context, contractArtifacts);
        AddArtifactContracts(context, contractArtifacts);

        var operations = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.OperationAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        var views = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.ViewAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        var derivationHosts = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.ServerDerivationAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol.ContainingSymbol))
            .Collect();

        // Behavior classes register from their OWN attributes (review round 4): [Gate]/[GateAll]
        // and [OnEffect] mirror [Operation]/[View] — declaration lives on the implementation.
        var gates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.GateAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        var wildcardGates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.GateAllAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        var subscribers = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.OnEffectAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        // Events are records (docs/31): a [DomainEvent] payload record IS the declaration —
        // discovery registers it and the contract derives from its members.
        var eventRecords = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.DomainEventAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        var all = operations.Combine(views).Combine(derivationHosts)
            .Combine(gates.Combine(wildcardGates).Combine(subscribers.Combine(eventRecords)));

        context.RegisterSourceOutput(all, static (spc, source) =>
        {
            var (((ops, viewTypes), hosts), ((gateTypes, wildcardTypes), (subscriberTypes, eventRecordTypes))) = source;
            if (ops.IsEmpty && viewTypes.IsEmpty && hosts.IsEmpty
                && gateTypes.IsEmpty && wildcardTypes.IsEmpty && subscriberTypes.IsEmpty
                && eventRecordTypes.IsEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> Tam.Compiler compile-time discovery.");
            sb.AppendLine("namespace Tam.Generated;");
            sb.AppendLine();
            // Internal: every assembly (host and each plugin) gets its own discovery class, and
            // referencing a plugin assembly must not make the host's AddDiscovered() ambiguous.
            sb.AppendLine("internal static class TamDiscovered");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Registers everything the compiler found — no runtime assembly scan.</summary>");
            sb.AppendLine("    public static global::Tam.TamModelBuilder AddDiscovered(this global::Tam.TamModelBuilder builder)");
            sb.AppendLine("    {");
            foreach (var op in ops.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddOperationType(typeof({op}));");
            foreach (var view in viewTypes.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddViewType(typeof({view}));");
            foreach (var host in hosts.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddDerivationHost(typeof({host}));");
            foreach (var gate in gateTypes.Concat(wildcardTypes).Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddGateType(typeof({gate}));");
            foreach (var subscriber in subscriberTypes.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddSubscriberType(typeof({subscriber}));");
            foreach (var eventRecord in eventRecordTypes.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddEventType(typeof({eventRecord}));");
            sb.AppendLine("        return builder;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>The plugin-scope twin: the same discoveries through the plugin's builder,");
            sb.AppendLine("    /// so a plugin's Configure needs only <c>plugin.AddDiscovered()</c>.</summary>");
            sb.AppendLine("    public static global::Tam.PluginBuilder AddDiscovered(this global::Tam.PluginBuilder plugin)");
            sb.AppendLine("    {");
            sb.AppendLine("        AddDiscovered(plugin.Model);");
            sb.AppendLine("        return plugin;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("TamDiscovered.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static string Qualified(ISymbol symbol) =>
        symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    // ---- Typed contract facades (docs/31): generated FROM this assembly's own
    // RequiresEvent/RequiresView declarations — compile-time names over the same
    // PLG008/PLG009-checked wire contract, never a reference to host CLR types. ----

    private static void AddContractFacades(
        IncrementalGeneratorInitializationContext context,
        IncrementalValueProvider<ImmutableArray<string>> contractArtifacts)
    {
        // "E|order-completed|orderId:guid|number" — a flat string per declaration keeps the
        // incremental pipeline trivially cacheable.
        var declarations = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is InvocationExpressionSyntax
            {
                ArgumentList.Arguments.Count: >= 2,
                Expression: MemberAccessExpressionSyntax
                {
                    Name.Identifier.ValueText: "RequiresEvent" or "RequiresView",
                },
            },
            static (ctx, ct) =>
            {
                var invocation = (InvocationExpressionSyntax)ctx.Node;
                if (ctx.SemanticModel.GetSymbolInfo(invocation, ct).Symbol is not IMethodSymbol method
                    || method.ContainingType.ToDisplayString() != "Tam.PluginBuilder")
                    return null;
                var parts = new System.Collections.Generic.List<string>
                {
                    method.Name == "RequiresEvent" ? "E" : "V",
                };
                foreach (var argument in invocation.ArgumentList.Arguments)
                {
                    if (argument.Expression is LiteralExpressionSyntax literal
                        && literal.IsKind(SyntaxKind.StringLiteralExpression))
                        parts.Add(literal.Token.ValueText);
                    else
                        return null;   // non-literal args: nothing to generate from
                }
                return string.Join("|", parts);
            })
            .Where(static d => d is not null)
            .Collect();

        context.RegisterSourceOutput(declarations.Combine(contractArtifacts), static (spc, source) =>
        {
            var (decls, artifacts) = source;
            // An artifact-backed plugin gets its facades from the artifact (below) — the
            // declaration-derived set would collide and is strictly poorer.
            if (artifacts.Any(a => a.Length > 0)) return;
            if (decls.IsEmpty) return;
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> Typed facades over this plugin's DECLARED wire");
            sb.AppendLine("// contracts (docs/31): sugar over the same PLG008/PLG009-checked names —");
            sb.AppendLine("// the wire contract stays the contract; no host CLR type is referenced.");
            sb.AppendLine("namespace Tam.Generated;");
            var seen = new System.Collections.Generic.HashSet<string>();
            foreach (var decl in decls.Distinct().OrderBy(x => x))
            {
                var parts = decl!.Split('|');
                var isEvent = parts[0] == "E";
                var target = parts[1];
                var typeName = Pascal(target) + (isEvent ? "Event" : "Row");
                if (!seen.Add(typeName)) continue;   // same target declared twice: first wins
                var fields = parts.Skip(2).Select(Field).ToArray();
                sb.AppendLine();
                sb.AppendLine($"/// <summary>Typed facade over the declared '{target}' "
                    + (isEvent ? "event contract." : "view read.") + "</summary>");
                sb.AppendLine($"internal sealed record {typeName}(");
                sb.AppendLine("    " + string.Join(",\n    ",
                    fields.Select(f => $"{f.Clr} {Pascal(f.Name)}")) + ")");
                sb.AppendLine("{");
                if (isEvent)
                {
                    sb.AppendLine($"    public const string EventType = \"{target}\";");
                    sb.AppendLine();
                    sb.AppendLine($"    public static {typeName} From(global::Tam.EffectEvent effect) => new(");
                    sb.AppendLine("        " + string.Join(",\n        ",
                        fields.Select(f => $"effect.{f.Accessor}(\"{f.Name}\")")) + ");");
                }
                else
                {
                    sb.AppendLine($"    public const string ViewId = \"{target}\";");
                    sb.AppendLine();
                    sb.AppendLine($"    public static {typeName} From(global::System.Text.Json.JsonElement row) => new(");
                    sb.AppendLine("        " + string.Join(",\n        ",
                        fields.Select(f => $"global::Tam.WireValues.{f.Accessor}(row, \"{f.Name}\")")) + ");");
                }
                sb.AppendLine("}");
            }
            spc.AddSource("TamContracts.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    // ---- Slice 3 (docs/31): facades + the HostContract index generated FROM the host's
    // exported contract artifact — the plugin references host-contract.json and the whole
    // extension surface becomes IntelliSense: HostContract.Events.*, HostContract.Views.*,
    // and a typed facade per event/view. Ids, fields and kinds ride the artifact. ----

    private static void AddArtifactContracts(
        IncrementalGeneratorInitializationContext context,
        IncrementalValueProvider<ImmutableArray<string>> contractArtifacts)
    {
        context.RegisterSourceOutput(contractArtifacts, static (spc, artifacts) =>
        {
            // Merge every referenced artifact (host contract + any parent-plugin slices, docs/37
            // D-V4). Order is stabilised so the generated file is deterministic regardless of the
            // order AdditionalFiles arrive in.
            var roots = artifacts
                .Where(a => a.Length > 0)
                .Select(a => MiniJson.Parse(a) as System.Collections.Generic.Dictionary<string, object?>)
                .Where(r => r is not null).Select(r => r!)
                .ToList();
            if (roots.Count == 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> The exported extension surface (docs/31 slice 3, docs/37 D-V4):");
            sb.AppendLine("// generated from host-contract.json plus any referenced <parent>.contract.json —");
            sb.AppendLine("// ids, fields and kinds ride the artifacts; PLG008/PLG009/PLG010 still verify every");
            sb.AppendLine("// requirement against the REAL composed host at Build(). Update the files to move versions.");
            sb.AppendLine("namespace Tam.Generated;");
            var seen = new System.Collections.Generic.HashSet<string>();
            var eventRefs = new System.Collections.Generic.List<(string Name, string Id, string[] Fields)>();
            var viewRefs = new System.Collections.Generic.List<(string Name, string Id, string[] Fields)>();

            foreach (var (id, fields) in roots.SelectMany(r => ContractEntries(r, "events")))
            {
                var typeName = Pascal(id) + "Event";
                if (!seen.Add(typeName)) continue;
                eventRefs.Add((Pascal(id), id, fields));
                EmitFacade(sb, typeName, id, fields, isEvent: true);
            }
            foreach (var (id, fields) in roots.SelectMany(r => ContractEntries(r, "views")))
            {
                var typeName = Pascal(id) + "Row";
                if (!seen.Add(typeName)) continue;
                viewRefs.Add((Pascal(id), id, fields));
                EmitFacade(sb, typeName, id, fields, isEvent: false);
            }

            sb.AppendLine();
            sb.AppendLine("/// <summary>The host's extension surface as symbols — browse with IntelliSense,");
            sb.AppendLine("/// require with <c>plugin.RequiresEvent(HostContract.Events.X)</c> /");
            sb.AppendLine("/// <c>plugin.RequiresView(HostContract.Views.Y, \"field\", …)</c>.</summary>");
            sb.AppendLine("internal static class HostContract");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class Events");
            sb.AppendLine("    {");
            foreach (var (name, id, fields) in eventRefs)
                sb.AppendLine($"        public static readonly global::Tam.EventContractRef {name} = "
                    + $"new(\"{id}\", new string[] {{ {string.Join(", ", fields.Select(f => $"\"{f}\""))} }});");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    internal static class Views");
            sb.AppendLine("    {");
            foreach (var (name, id, fields) in viewRefs)
                sb.AppendLine($"        public static readonly global::Tam.ViewContractRef {name} = "
                    + $"new(\"{id}\", new string[] {{ {string.Join(", ", fields.Select(f => $"\"{f}\""))} }});");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>Operation ids as CONSTS — usable in attributes:");
            sb.AppendLine("    /// <c>[Gate(HostContract.Operations.OrdersComplete)]</c>.</summary>");
            sb.AppendLine("    internal static class Operations");
            sb.AppendLine("    {");
            foreach (var operation in roots.SelectMany(r => StringListSection(r, "operations")).Distinct())
                sb.AppendLine($"        public const string {Pascal(operation)} = \"{operation}\";");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    internal static class Slots");
            sb.AppendLine("    {");
            var slotSeen = new System.Collections.Generic.HashSet<string>();
            foreach (var (slotId, keys) in roots.SelectMany(SlotEntries))
            {
                if (!slotSeen.Add(slotId)) continue;
                sb.AppendLine($"        public static readonly global::Tam.SlotContractRef {Pascal(slotId)} = "
                    + $"new(\"{slotId}\", new string[] {{ {string.Join(", ", keys.Select(k => $"\"{k}\""))} }});");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    internal static class Entities");
            sb.AppendLine("    {");
            foreach (var entity in roots.SelectMany(r => StringListSection(r, "extensibleEntities")).Distinct())
                sb.AppendLine($"        public static readonly global::Tam.EntityContractRef {Pascal(entity)} = "
                    + $"new(\"{entity}\");");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    internal static class Grids");
            sb.AppendLine("    {");
            foreach (var gridId in roots.SelectMany(r => SectionKeys(r, "grids")).Distinct())
                sb.AppendLine($"        public static readonly global::Tam.GridContractRef {Pascal(gridId)} = "
                    + $"new(\"{gridId}\");");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("TamHostContract.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static System.Collections.Generic.IEnumerable<string> StringListSection(
        System.Collections.Generic.Dictionary<string, object?> root, string section) =>
        root.TryGetValue(section, out var value)
            && value is System.Collections.Generic.List<object?> list
        ? list.OfType<string>()
        : [];

    private static System.Collections.Generic.IEnumerable<string> SectionKeys(
        System.Collections.Generic.Dictionary<string, object?> root, string section) =>
        root.TryGetValue(section, out var value)
            && value is System.Collections.Generic.Dictionary<string, object?> entries
        ? entries.Keys.OrderBy(k => k, System.StringComparer.Ordinal)
        : [];

    private static System.Collections.Generic.IEnumerable<(string Id, string[] Keys)> SlotEntries(
        System.Collections.Generic.Dictionary<string, object?> root)
    {
        if (root.TryGetValue("slots", out var value)
            && value is System.Collections.Generic.Dictionary<string, object?> slots)
        {
            foreach (var entry in slots.OrderBy(e => e.Key, System.StringComparer.Ordinal))
            {
                var keys = entry.Value is System.Collections.Generic.Dictionary<string, object?> body
                    && body.TryGetValue("keys", out var k)
                    && k is System.Collections.Generic.List<object?> list
                    ? list.OfType<string>().ToArray()
                    : [];
                yield return (entry.Key, keys);
            }
        }
    }

    /// <summary>Reads one contract section into (id, kinded field strings) — fields rejoin
    /// their kinds ("orderId:guid") so downstream reuses the one declared-field grammar.</summary>
    private static System.Collections.Generic.IEnumerable<(string Id, string[] Fields)> ContractEntries(
        System.Collections.Generic.Dictionary<string, object?> root, string section)
    {
        if (root.TryGetValue(section, out var value)
            && value is System.Collections.Generic.Dictionary<string, object?> entries)
        {
            foreach (var entry in entries.OrderBy(e => e.Key, System.StringComparer.Ordinal))
            {
                if (entry.Value is not System.Collections.Generic.Dictionary<string, object?> body) continue;
                var kinds = body.TryGetValue("kinds", out var k)
                    && k is System.Collections.Generic.Dictionary<string, object?> kd
                    ? kd : new System.Collections.Generic.Dictionary<string, object?>();
                var fields = body.TryGetValue("fields", out var f)
                    && f is System.Collections.Generic.List<object?> list
                    ? list.OfType<string>()
                        .Select(name => kinds.TryGetValue(name, out var kind) && kind is string s
                            ? $"{name}:{s}" : name)
                        .ToArray()
                    : [];
                yield return (entry.Key, fields);
            }
        }
    }

    private static void EmitFacade(
        StringBuilder sb, string typeName, string target, string[] fields, bool isEvent)
    {
        var parsed = fields.Select(Field).ToArray();
        if (parsed.Length == 0) return;
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Typed facade over the host's '{target}' "
            + (isEvent ? "event contract" : "view") + " (from host-contract.json).</summary>");
        sb.AppendLine($"internal sealed record {typeName}(");
        sb.AppendLine("    " + string.Join(",\n    ",
            parsed.Select(f => $"{f.Clr} {Pascal(f.Name)}")) + ")");
        sb.AppendLine("{");
        if (isEvent)
        {
            sb.AppendLine($"    public const string EventType = \"{target}\";");
            sb.AppendLine();
            sb.AppendLine($"    public static {typeName} From(global::Tam.EffectEvent effect) => new(");
            sb.AppendLine("        " + string.Join(",\n        ",
                parsed.Select(f => $"effect.{f.Accessor}(\"{f.Name}\")")) + ");");
        }
        else
        {
            sb.AppendLine($"    public const string ViewId = \"{target}\";");
            sb.AppendLine();
            sb.AppendLine($"    public static {typeName} From(global::System.Text.Json.JsonElement row) => new(");
            sb.AppendLine("        " + string.Join(",\n        ",
                parsed.Select(f => $"global::Tam.WireValues.{f.Accessor}(row, \"{f.Name}\")")) + ");");
        }
        sb.AppendLine("}");
    }

    private static (string Name, string Clr, string Accessor) Field(string declared)
    {
        var split = declared.Split(':');
        var kind = split.Length > 1 ? split[1] : "string";
        var (clr, accessor) = kind switch
        {
            "guid" => ("global::System.Guid?", "Guid"),
            "decimal" => ("decimal?", "Decimal"),
            "int" => ("int?", "Int"),
            "bool" => ("bool?", "Bool"),
            _ => ("string?", "String"),
        };
        return (split[0], clr, accessor);
    }

    private static string Pascal(string wire) =>
        string.Concat(wire
            .Split('-', '.', '_')
            .Where(static part => part.Length > 0)
            .Select(static part => char.ToUpperInvariant(part[0]) + part.Substring(1)));
}

/// <summary>A minimal JSON reader for the host contract artifact — the generator runs inside
/// the compiler process where package dependencies don't resolve reliably, and the artifact's
/// shape is OURS (objects, arrays, strings; numbers/bools/null tolerated and skipped). Objects
/// → Dictionary&lt;string, object?&gt;, arrays → List&lt;object?&gt;, strings → string.</summary>
internal static class MiniJson
{
    public static object? Parse(string text)
    {
        var i = 0;
        try
        {
            var value = ParseValue(text, ref i);
            return value;
        }
        catch (System.Exception)
        {
            return null;   // a malformed artifact generates nothing; Build() still verifies
        }
    }

    private static object? ParseValue(string s, ref int i)
    {
        SkipWs(s, ref i);
        switch (s[i])
        {
            case '{':
                var obj = new System.Collections.Generic.Dictionary<string, object?>();
                i++;
                SkipWs(s, ref i);
                if (s[i] == '}') { i++; return obj; }
                while (true)
                {
                    SkipWs(s, ref i);
                    var key = ParseString(s, ref i);
                    SkipWs(s, ref i);
                    i++;   // ':'
                    obj[key] = ParseValue(s, ref i);
                    SkipWs(s, ref i);
                    if (s[i] == ',') { i++; continue; }
                    i++;   // '}'
                    return obj;
                }
            case '[':
                var list = new System.Collections.Generic.List<object?>();
                i++;
                SkipWs(s, ref i);
                if (s[i] == ']') { i++; return list; }
                while (true)
                {
                    list.Add(ParseValue(s, ref i));
                    SkipWs(s, ref i);
                    if (s[i] == ',') { i++; continue; }
                    i++;   // ']'
                    return list;
                }
            case '"':
                return ParseString(s, ref i);
            default:
                // number / true / false / null — tolerated, value dropped to null
                while (i < s.Length && s[i] != ',' && s[i] != '}' && s[i] != ']') i++;
                return null;
        }
    }

    private static string ParseString(string s, ref int i)
    {
        i++;   // opening quote
        var sb = new StringBuilder();
        while (s[i] != '"')
        {
            if (s[i] == '\\')
            {
                i++;
                sb.Append(s[i] switch
                {
                    'n' => '\n', 't' => '\t', 'r' => '\r',
                    'u' => (char)System.Convert.ToInt32(s.Substring(i + 1, 4), 16),
                    _ => s[i],
                });
                if (s[i] == 'u') i += 4;
            }
            else
            {
                sb.Append(s[i]);
            }
            i++;
        }
        i++;   // closing quote
        return sb.ToString();
    }

    private static void SkipWs(string s, ref int i)
    {
        while (i < s.Length && char.IsWhiteSpace(s[i])) i++;
    }
}
