using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Tam.Compiler;

/// <summary>
/// Compile-time discovery (docs/12): emits an <c>AddDiscovered()</c> extension registering every
/// [Operation], [View], and [ServerDerivation] host in the compilation — the model is explicit,
/// generated, and inspectable on disk instead of found by runtime assembly scanning (docs/01).
/// </summary>
[Generator]
public sealed class TamSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        AddContractFacades(context);

        var operations = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.OperationAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        var views = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.ViewAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        var derivationHosts = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.ServerDerivationAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol.ContainingSymbol))
            .Collect();

        // Behavior classes register from their OWN attributes (review round 4): [Gate]/[GateAll]
        // and [OnEffect] mirror [Operation]/[View] — declaration lives on the implementation.
        var gates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.GateAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        var wildcardGates = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.GateAllAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        var subscribers = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.OnEffectAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        // Events are records (docs/31): a [DomainEvent] payload record IS the declaration —
        // discovery registers it and the contract derives from its members.
        var eventRecords = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Tam.DomainEventAttribute",
            static (_, _) => true,
            static (ctx, _) => Qualified(ctx.TargetSymbol))
            .Collect();

        var all = operations.Combine(views).Combine(derivationHosts)
            .Combine(gates.Combine(wildcardGates).Combine(subscribers.Combine(eventRecords)));

        context.RegisterSourceOutput(all, static (spc, source) =>
        {
            var (((ops, viewTypes), hosts), ((gateTypes, wildcardTypes), (subscriberTypes, eventRecordTypes))) = source;
            if (ops.IsEmpty && viewTypes.IsEmpty && hosts.IsEmpty
                && gateTypes.IsEmpty && wildcardTypes.IsEmpty && subscriberTypes.IsEmpty
                && eventRecordTypes.IsEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> Tam.Compiler compile-time discovery.");
            sb.AppendLine("namespace Tam.Generated;");
            sb.AppendLine();
            // Internal: every assembly (host and each plugin) gets its own discovery class, and
            // referencing a plugin assembly must not make the host's AddDiscovered() ambiguous.
            sb.AppendLine("internal static class TamDiscovered");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Registers everything the compiler found — no runtime assembly scan.</summary>");
            sb.AppendLine("    public static global::Tam.TamModelBuilder AddDiscovered(this global::Tam.TamModelBuilder builder)");
            sb.AppendLine("    {");
            foreach (var op in ops.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddOperationType(typeof({op}));");
            foreach (var view in viewTypes.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddViewType(typeof({view}));");
            foreach (var host in hosts.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddDerivationHost(typeof({host}));");
            foreach (var gate in gateTypes.Concat(wildcardTypes).Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddGateType(typeof({gate}));");
            foreach (var subscriber in subscriberTypes.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddSubscriberType(typeof({subscriber}));");
            foreach (var eventRecord in eventRecordTypes.Distinct().OrderBy(x => x))
                sb.AppendLine($"        builder.AddEventType(typeof({eventRecord}));");
            sb.AppendLine("        return builder;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>The plugin-scope twin: the same discoveries through the plugin's builder,");
            sb.AppendLine("    /// so a plugin's Configure needs only <c>plugin.AddDiscovered()</c>.</summary>");
            sb.AppendLine("    public static global::Tam.PluginBuilder AddDiscovered(this global::Tam.PluginBuilder plugin)");
            sb.AppendLine("    {");
            sb.AppendLine("        AddDiscovered(plugin.Model);");
            sb.AppendLine("        return plugin;");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("TamDiscovered.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static string Qualified(ISymbol symbol) =>
        symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    // ---- Typed contract facades (docs/31): generated FROM this assembly's own
    // RequiresEvent/RequiresView declarations — compile-time names over the same
    // PLG008/PLG009-checked wire contract, never a reference to host CLR types. ----

    private static void AddContractFacades(IncrementalGeneratorInitializationContext context)
    {
        // "E|order-completed|orderId:guid|number" — a flat string per declaration keeps the
        // incremental pipeline trivially cacheable.
        var declarations = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is InvocationExpressionSyntax
            {
                ArgumentList.Arguments.Count: >= 2,
                Expression: MemberAccessExpressionSyntax
                {
                    Name.Identifier.ValueText: "RequiresEvent" or "RequiresView",
                },
            },
            static (ctx, ct) =>
            {
                var invocation = (InvocationExpressionSyntax)ctx.Node;
                if (ctx.SemanticModel.GetSymbolInfo(invocation, ct).Symbol is not IMethodSymbol method
                    || method.ContainingType.ToDisplayString() != "Tam.PluginBuilder")
                    return null;
                var parts = new System.Collections.Generic.List<string>
                {
                    method.Name == "RequiresEvent" ? "E" : "V",
                };
                foreach (var argument in invocation.ArgumentList.Arguments)
                {
                    if (argument.Expression is LiteralExpressionSyntax literal
                        && literal.IsKind(SyntaxKind.StringLiteralExpression))
                        parts.Add(literal.Token.ValueText);
                    else
                        return null;   // non-literal args: nothing to generate from
                }
                return string.Join("|", parts);
            })
            .Where(static d => d is not null)
            .Collect();

        context.RegisterSourceOutput(declarations, static (spc, decls) =>
        {
            if (decls.IsEmpty) return;
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/> Typed facades over this plugin's DECLARED wire");
            sb.AppendLine("// contracts (docs/31): sugar over the same PLG008/PLG009-checked names —");
            sb.AppendLine("// the wire contract stays the contract; no host CLR type is referenced.");
            sb.AppendLine("namespace Tam.Generated;");
            var seen = new System.Collections.Generic.HashSet<string>();
            foreach (var decl in decls.Distinct().OrderBy(x => x))
            {
                var parts = decl!.Split('|');
                var isEvent = parts[0] == "E";
                var target = parts[1];
                var typeName = Pascal(target) + (isEvent ? "Event" : "Row");
                if (!seen.Add(typeName)) continue;   // same target declared twice: first wins
                var fields = parts.Skip(2).Select(Field).ToArray();
                sb.AppendLine();
                sb.AppendLine($"/// <summary>Typed facade over the declared '{target}' "
                    + (isEvent ? "event contract." : "view read.") + "</summary>");
                sb.AppendLine($"internal sealed record {typeName}(");
                sb.AppendLine("    " + string.Join(",\n    ",
                    fields.Select(f => $"{f.Clr} {Pascal(f.Name)}")) + ")");
                sb.AppendLine("{");
                if (isEvent)
                {
                    sb.AppendLine($"    public const string EventType = \"{target}\";");
                    sb.AppendLine();
                    sb.AppendLine($"    public static {typeName} From(global::Tam.EffectEvent effect) => new(");
                    sb.AppendLine("        " + string.Join(",\n        ",
                        fields.Select(f => $"effect.{f.Accessor}(\"{f.Name}\")")) + ");");
                }
                else
                {
                    sb.AppendLine($"    public const string ViewId = \"{target}\";");
                    sb.AppendLine();
                    sb.AppendLine($"    public static {typeName} From(global::System.Text.Json.JsonElement row) => new(");
                    sb.AppendLine("        " + string.Join(",\n        ",
                        fields.Select(f => $"global::Tam.WireValues.{f.Accessor}(row, \"{f.Name}\")")) + ");");
                }
                sb.AppendLine("}");
            }
            spc.AddSource("TamContracts.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static (string Name, string Clr, string Accessor) Field(string declared)
    {
        var split = declared.Split(':');
        var kind = split.Length > 1 ? split[1] : "string";
        var (clr, accessor) = kind switch
        {
            "guid" => ("global::System.Guid?", "Guid"),
            "decimal" => ("decimal?", "Decimal"),
            "int" => ("int?", "Int"),
            "bool" => ("bool?", "Bool"),
            _ => ("string?", "String"),
        };
        return (split[0], clr, accessor);
    }

    private static string Pascal(string wire) =>
        string.Concat(wire
            .Split('-', '.', '_')
            .Where(static part => part.Length > 0)
            .Select(static part => char.ToUpperInvariant(part[0]) + part.Substring(1)));
}
